# ##################配置端口####################
server:
  port: 9000
#####################配置注册中心###############
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
####################配置服务名字#####################
spring:
  application:
    name: ZuulEureka
################ Zuul动态服务配置服务路由 #########################
zuul:
  routes:
    #   aaaaa: 可以随便写
    aaaa:
      path: /myservice/**
      # 服务名
      serviceId: serviceeureka
      # 设置Cookie可传递
      #sensitiveHeaders:
    ####简洁写法
    #serviceeureka: /myservice/**
  #禁止外部访问(排除某些路由) 接口 是set集合
  ignored-patterns:
    - /myservice/getAll
    #- /serviceeureka/getAll
    #- /**/getAll

    #忽略全部服务敏感头都可传递Cookie
  sensitive-headers: